<?php

namespace app\modules\frontend\controllers;

use app\models\DoanhNghiep;
use app\models\HoKinhDoanh;
use app\models\TinTuc;
use app\models\VDoanhnghiep;
use app\modules\frontend\models\FormLienhe;
use app\modules\frontend\base\FrontendBaseController;
use app\services\DebugService;
use app\services\UtilityService;
use Yii;
use yii\data\Pagination;
use yii\db\Expression;
use const YII_ENV_TEST;
use function mb_strtoupper;

class SiteController extends FrontendBaseController {


    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
//        $this->layout = "@app/modules/frontend/views/layouts/main";
        $model['tin_tuc']=  TinTuc::find()->limit(4)->all();
        $model['doanh_nghiep']=  VDoanhnghiep::find()->where(['tieu_bieu' => 1])->orderBy(new Expression('random()'))->limit(4)->all();
        return $this->render('index',[
            'model' => $model
        ]);
    }

    /**
     * Displays map page.
     *
     * @return string
     */
    public function actionMap() {
        $this->layout = "@app/views/layouts/layout_map";
        return $this->render('map');
    }

    public function actionSearch() {
        // DebugService::dumpdie(Yii::$app->request->post());
        $post = Yii::$app->request->post();
        // $chuyengia = " ho_ten like '%" . mb_strtoupper($post['ho_ten']) . "%'";
        return $this->redirect(Yii::$app->homeUrl . 'site/map?key=1=1%20and%20ten_hkd%20like%20%27%25' . mb_strtoupper($post['ten_hkd']) . '%25%27');
    }

    public function actionTest() {
        $model = null;
        return $this->render('test', [
                    'model' => $model
        ]);
    }

    public function actionHuongdan() {
        $this->layout = "@app/views/layouts/user/main_user";
        return $this->render('huongdan');
    }

    public function actionAbout() {
        $this->layout = "@app/views/layouts/user/main_user";
        return $this->render('about');
    }

    public function actionContact(){
        $model = new FormLienhe();
        return $this->render('contact',[
            'model' => $model
        ]);
    }
    public function actionTinTuc(){

    }

//    public function actionContact() {
//        $hkd = HoKinhDoanh::find()->count();
//        $dn = DoanhNghiep::find()->count();
//        $model['tin_tuc']=  TinTuc::find()->all();
//        $query = VDoanhnghiep::find()->where(['tieu_bieu' => 1]);
//        $count = $query->count();
//        $pages = new Pagination(['totalCount' => $count, 'pageSize' => 30]);
//
//        $model['doanhnghiep_tieubieu'] = $query->offset($pages->offset)
//                ->limit($pages->limit)
//                ->all();
//        //  \app\services\DebugService::dumpdie($model['tieu_bieu']);
//        $this->layout = "@app/views/layouts/user/main_user";
//        return $this->render('contact', ['pages' => $pages,
//                    'totalcount' => $count,
//                    'hkd' => $hkd,
//                    'dn' => $dn,
//                    'model' => $model]);
//    }

    public function actionVitri($id = null) {
        $request = Yii::$app->request;
        $post = $request->post();
        if (!UtilityService::paramValidate($id)) {
            return $this->redirect(\Yii::$app->urlManager->createUrl('site/contact'));
        }

        $model['toado'] = VDoanhnghiep::findOne($id);
        if ($model['toado'] == null) {
            return $this->redirect(\Yii::$app->urlManager->createUrl('site/contact'));
        }

        return $this->renderPartial('vitri', [
                    'model' => $model
        ]);
    }

}
