<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_diemgiuxe".
 *
 * @property integer $id_diemgiuxe
 * @property string $ten_diemgiuxe
 * @property string $so_nha
 * @property string $ten_duong
 * @property string $ten_phuong
 * @property string $tien_phi
 * @property string $coquan_quanly
 * @property string $geom
 * @property string $ghi_chu
 * @property string $chu_dau_tu
 * @property integer $dien_tich
 * @property string $quy_mo
 * @property string $tien_ich
 * @property string $dien_thoai
 * @property double $geo_x
 * @property double $geo_y
 */
class VDiemgiuxe extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_diemgiuxe';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_diemgiuxe', 'dien_tich'], 'integer'],
            [['ten_diemgiuxe', 'so_nha', 'ten_duong', 'ten_phuong', 'coquan_quanly', 'geom', 'ghi_chu', 'chu_dau_tu', 'quy_mo', 'tien_ich', 'dien_thoai'], 'string'],
            [['tien_phi', 'geo_x', 'geo_y'], 'number'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_diemgiuxe' => 'Id Diemgiuxe',
            'ten_diemgiuxe' => 'Tên',
            'so_nha' => 'Số nhà',
            'ten_duong' => 'Tên đường',
            'ten_phuong' => 'Tên phường',
            'tien_phi' => 'Tiền phí',
            'coquan_quanly' => 'Cơ quan quản lý',
            'geom' => 'Geom',
            'ghi_chu' => 'Ghi chú',
            'chu_dau_tu' => 'Chủ đầu tư',
            'dien_tich' => 'Diện tích',
            'quy_mo' => 'Quy mô',
            'tien_ich' => 'Tiện ích',
            'dien_thoai' => 'Điện thoại',
            'geo_x' => 'Geo X',
            'geo_y' => 'Geo Y',
        ];
    }
      public static function primaryKey() {
        return ['id_diemgiuxe']; // TODO: Change the autogenerated stub
    }
}
